name: CI pipeline
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build
        run: chmod +x gradlew && ./gradlew build -x test
      - name: Tests
        run: ./gradlew test 
      - name: Run coverage
        run: |
          chmod +x gradlew
          ./gradlew build jacocoTestReport
      - name: Jacoco archive
        uses: actions/upload-artifact@v4
        with:
            name: code-coverage-report
            path: build/reports 
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available

      - name: Build
        run: chmod +x gradlew && ./gradlew build -x test && ls -lrth build/libs/
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build dockerfile and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
	    shrikumarudupa/java-app:latest
	    shrikumarudupa/java-app:-${{ github.run_number }}

  modifygit:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'Shrikumar-Udupa/java-app-deploy'
          token: ${{ secrets.GIT_PASSWORD }}
      - name: modify the image
        run: |
          git config user.email shrikumarudupa99@gmail.com
          git config user.name Shrikumar
          pwd
          cat manifest/deployment.yaml
          pwd
          sed -i "s+shrikumarudupa/java-app:*+shrikumarudupa/java-app:$RUN_NUMBER+g" manifest/deployment.yaml
          cat manifest/deployment.yaml
          git add .
          git commit -m 'Manifest update by Github Actions Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}